package com.Leon.pojo;
// Generated 2019-1-2 0:12:42 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * New generated by hbm2java
 */
@Entity
@Table(name = "new", catalog = "cms")
public class New implements java.io.Serializable {

	private Integer id;
	private String title;
	private Date date;
	private String sketch;
	private String detail;
	private String image;
	private String images;
	private int state;
	private String author;

	public New() {
	}

	public New(String title, Date date, String sketch, String image, int state) {
		this.title = title;
		this.date = date;
		this.sketch = sketch;
		this.image = image;
		this.state = state;
	}

	public New(String title, Date date, String sketch, String detail, String image, String images, int state,
			String author) {
		this.title = title;
		this.date = date;
		this.sketch = sketch;
		this.detail = detail;
		this.image = image;
		this.images = images;
		this.state = state;
		this.author = author;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "title", nullable = false, length = 32)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date", nullable = false, length = 10)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Column(name = "sketch", nullable = false, length = 128)
	public String getSketch() {
		return this.sketch;
	}

	public void setSketch(String sketch) {
		this.sketch = sketch;
	}

	@Column(name = "detail", length = 1024)
	public String getDetail() {
		return this.detail;
	}

	public void setDetail(String detail) {
		this.detail = detail;
	}

	@Column(name = "image", nullable = false, length = 128)
	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	@Column(name = "images", length = 128)
	public String getImages() {
		return this.images;
	}

	public void setImages(String images) {
		this.images = images;
	}

	@Column(name = "state", nullable = false)
	public int getState() {
		return this.state;
	}

	public void setState(int state) {
		this.state = state;
	}

	@Column(name = "author", length = 16)
	public String getAuthor() {
		return this.author;
	}

	public void setAuthor(String author) {
		this.author = author;
	}

}
