package com.Leon.pojo;
// Generated 2019-1-2 0:12:42 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name = "product", catalog = "cms")
public class Product implements java.io.Serializable {

	private Integer id;
	private String name;
	private String type;
	private Date date;
	private String sketch;
	private String details;
	private String image;
	private String images;
	private int state;
	private String author;
	private String brand;
	private Float price;
	private String size;
	private String weight;
	private String cpu;
	private String ram;
	private String rom;
	private String battery;

	public Product() {
	}

	public Product(String name, String type, Date date, String sketch, String image, int state) {
		this.name = name;
		this.type = type;
		this.date = date;
		this.sketch = sketch;
		this.image = image;
		this.state = state;
	}

	public Product(String name, String type, Date date, String sketch, String details, String image, String images,
			int state, String author, String brand, Float price, String size, String weight, String cpu, String ram,
			String rom, String battery) {
		this.name = name;
		this.type = type;
		this.date = date;
		this.sketch = sketch;
		this.details = details;
		this.image = image;
		this.images = images;
		this.state = state;
		this.author = author;
		this.brand = brand;
		this.price = price;
		this.size = size;
		this.weight = weight;
		this.cpu = cpu;
		this.ram = ram;
		this.rom = rom;
		this.battery = battery;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 16)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "type", nullable = false, length = 16)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date", nullable = false, length = 10)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Column(name = "sketch", nullable = false, length = 128)
	public String getSketch() {
		return this.sketch;
	}

	public void setSketch(String sketch) {
		this.sketch = sketch;
	}

	@Column(name = "details", length = 1024)
	public String getDetails() {
		return this.details;
	}

	public void setDetails(String details) {
		this.details = details;
	}

	@Column(name = "image", nullable = false, length = 128)
	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	@Column(name = "images", length = 128)
	public String getImages() {
		return this.images;
	}

	public void setImages(String images) {
		this.images = images;
	}

	@Column(name = "state", nullable = false)
	public int getState() {
		return this.state;
	}

	public void setState(int state) {
		this.state = state;
	}

	@Column(name = "author", length = 16)
	public String getAuthor() {
		return this.author;
	}

	public void setAuthor(String author) {
		this.author = author;
	}

	@Column(name = "brand", length = 16)
	public String getBrand() {
		return this.brand;
	}

	public void setBrand(String brand) {
		this.brand = brand;
	}

	@Column(name = "price", precision = 12, scale = 0)
	public Float getPrice() {
		return this.price;
	}

	public void setPrice(Float price) {
		this.price = price;
	}

	@Column(name = "size", length = 16)
	public String getSize() {
		return this.size;
	}

	public void setSize(String size) {
		this.size = size;
	}

	@Column(name = "weight", length = 16)
	public String getWeight() {
		return this.weight;
	}

	public void setWeight(String weight) {
		this.weight = weight;
	}

	@Column(name = "cpu", length = 16)
	public String getCpu() {
		return this.cpu;
	}

	public void setCpu(String cpu) {
		this.cpu = cpu;
	}

	@Column(name = "ram", length = 16)
	public String getRam() {
		return this.ram;
	}

	public void setRam(String ram) {
		this.ram = ram;
	}

	@Column(name = "rom", length = 16)
	public String getRom() {
		return this.rom;
	}

	public void setRom(String rom) {
		this.rom = rom;
	}

	@Column(name = "battery", length = 16)
	public String getBattery() {
		return this.battery;
	}

	public void setBattery(String battery) {
		this.battery = battery;
	}

}
