/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.0-RC5
 * Generated at: 2020-01-02 12:51:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.web_005ffront.conference;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class conferences_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fstep_005fend_005fbegin;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fstep_005fend_005fbegin = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fstep_005fend_005fbegin.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"utf-8\" />\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\" />\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />\n");
      out.write("    <title>TECH-发布会</title>\n");
      out.write("    <!-- web-fonts -->\n");
      out.write("    <link href='https://fonts.googleapis.com/css?family=Roboto:100,300,400,700,500' rel='stylesheet' type='text/css' />\n");
      out.write("    <!-- favicon -->\n");
      out.write("    <link href=\"../assets/img/favicon.png\" rel=\"icon\" />\n");
      out.write("    <!-- Bootstrap -->\n");
      out.write("    <link href=\"../assets/css/bootstrap.min.css\" rel=\"stylesheet\" />\n");
      out.write("     <!--font-awesome--> \n");
      out.write("    <link href=\"../assets/fonts/font-awesome/font-awesome.min.css\" rel=\"stylesheet\" />\n");
      out.write("     <!--Mobile Menu Style--> \n");
      out.write("    <link href=\"../assets/css/mobile-menu.css\" rel=\"stylesheet\" />\n");
      out.write("     <!--Owl carousel--> \n");
      out.write("    <link href=\"../assets/css/owl.carousel.css\" rel=\"stylesheet\" />\n");
      out.write("    <link href=\"../assets/css/owl.theme.default.min.css\" rel=\"stylesheet\" />\n");
      out.write("     <!--Theme Style--> \n");
      out.write("    <link href=\"../assets/css/style.css\" rel=\"stylesheet\" />\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body id=\"page-top\" data-spy=\"scroll\" data-target=\".navbar\">\n");
      out.write("<div id=\"main-wrapper\">\n");
      out.write("<!-- Page Preloader -->\n");
      out.write("<div id=\"preloader\"><div id=\"status\"><div class=\"status-mes\"></div></div></div>\n");
      out.write("<!-- preloader -->\n");
      out.write("<div class=\"uc-mobile-menu-pusher\">\n");
      out.write("<div class=\"content-wrapper\">\n");
      out.write("<section id=\"header_section_wrapper\" class=\"header_section_wrapper\">\n");
      out.write("     <div class=\"container\">\n");
      out.write("         <div class=\"header-section\">\n");
      out.write("             <div class=\"row\">\n");
      out.write("                 <div class=\"col-md-4\">\n");
      out.write("                     <div class=\"left_section\">\n");
      out.write("                         <span class=\"date\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${util.getDateTime() }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</span>\n");
      out.write("                      <!-- Date -->\n");
      out.write("                      <div class=\"social\">\n");
      out.write("                          <a class=\"icons-sm fb-ic\"><i class=\"fa fa-facebook\"></i></a>\n");
      out.write("                          <a class=\"icons-sm tw-ic\"><i class=\"fa fa-twitter\"></i></a>\n");
      out.write("                          <a class=\"icons-sm inst-ic\"><i class=\"fa fa-instagram\"> </i></a>\n");
      out.write("                          <a class=\"icons-sm tmb-ic\"><i class=\"fa fa-tumblr\"> </i></a>\n");
      out.write("                          <a class=\"icons-sm rss-ic\"><i class=\"fa fa-rss\"> </i></a>\n");
      out.write("                      </div>\n");
      out.write("                      <!-- Top Social Section -->\n");
      out.write("                  </div>\n");
      out.write("                  <!-- Left Header Section -->\n");
      out.write("              </div>\n");
      out.write("              <div class=\"col-md-4\">\n");
      out.write("                  <div class=\"logo\">\n");
      out.write("                      <a href=\"#\"><img src=\"../assets/img/logo.png\" alt=\"Tech NewsLogo\" /></a>\n");
      out.write("                  </div>\n");
      out.write("                  <!-- Logo Section -->\n");
      out.write("              </div>\n");
      out.write("              <div class=\"col-md-4\">\n");
      out.write("                  <div class=\"right_section\">\n");
      out.write("                      <ul class=\"nav navbar-nav\">\n");
      out.write("\t\n");
      out.write("       \t\t\t\t\t<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/login.jsp\">Login</a></li>\n");
      out.write("                        <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/front/back\">Register</a></li>\n");
      out.write("                      </ul>\n");
      out.write("                      <!-- LogAndReg Section -->\n");
      out.write("                      <ul class=\"nav-cta hidden-xs\">\n");
      out.write("                          <li class=\"dropdown\"><a href=\"#\" data-toggle=\"dropdown\" class=\"dropdown-toggle\"><i class=\"fa fa-search\"></i></a>\n");
      out.write("                              <ul class=\"dropdown-menu\"><li>\n");
      out.write("                                      <div class=\"head-search\">\n");
      out.write("\n");
      out.write("                                   \t<form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/conf/searchByKey\" method=\"post\" >\n");
      out.write("                                          <div class=\"input-group\">\n");
      out.write("                                          <input  name=\"key\" type=\"text\" class=\"form-control\" placeholder=\"请输入关键字\" ></input>    \n");
      out.write("                                              <span class=\"input-group-btn\">\n");
      out.write("                                              \t<input  type=\"submit\" value=\"查询\" class=\"btn btn-primary\"></input>\n");
      out.write("                                              </span> \n");
      out.write("                                          </div>\n");
      out.write("                                   \t</form>   \n");
      out.write("                                      </div></li></ul></li>\n");
      out.write("                      </ul>\n");
      out.write("                      <!-- Search Section--> \n");
      out.write("                  </div>\n");
      out.write("                  <!-- Right Header Section -->\n");
      out.write("              </div>\n");
      out.write("          </div>\n");
      out.write("      </div>\n");
      out.write("      <!-- Header Section -->\n");
      out.write("\n");
      out.write("      <div class=\"navigation-section\">\n");
      out.write("          <nav class=\"navbar m-menu navbar-default\">\n");
      out.write("              <div class=\"container\">\n");
      out.write("                  <div class=\"collapse navbar-collapse\" id=\"#navbar-collapse-1\">\n");
      out.write("                      <ul class=\"nav navbar-nav main-nav\">\n");
      out.write("                          <li>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</li>\n");
      out.write("                          <!--<li class=\"active\"><a>首页</a></li>-->\n");
      out.write("\n");
      out.write("                          <li class=\"active\"><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/front/home\">首页</a></li>\n");
      out.write("                          <li>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</li>\n");
      out.write("                          <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/conf/showRefreh\">发布会</a></li>\n");
      out.write("                          <li>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</li>\n");
      out.write("                          <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/news/showRefreh\">新闻</a></li>\n");
      out.write("                          <li>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</li>\n");
      out.write("                          <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/video/showRefreh\">视频</a></li>\n");
      out.write("                          <li>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</li>\n");
      out.write("                          <li class=\"dropdown m-menu-fw\">\n");
      out.write("                              <a href=\"#\" data-toggle=\"dropdown\" class=\"dropdown-toggle\">产品               \n");
      out.write("                              <span><i class=\"fa fa-angle-down\"></i></span></a>\n");
      out.write("                              <ul class=\"dropdown-menu\"> \t<li>\n");
      out.write("\n");
      out.write("                                  <div class=\"m-menu-content\">\n");
      out.write("                                      <span><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/product/showProducts?type=phone\"  class=\"dropdown-header\">手机</a></span>&nbsp;\n");
      out.write("                                      <span><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/product/showProducts?type=computer\"  class=\"dropdown-header\">电脑</a></span>&nbsp;\n");
      out.write("                                      <span><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/product/showProducts?type=other\"  class=\"dropdown-header\">其他</a></span>&nbsp;\n");
      out.write("                                  </div></li>\n");
      out.write("                              </ul></li>\n");
      out.write("                      </ul>\n");
      out.write("                  </div>\n");
      out.write("              </div>\n");
      out.write("              <!-- .container -->\n");
      out.write("          </nav>\n");
      out.write("          <!-- .nav -->\n");
      out.write("      </div>\n");
      out.write("      <!-- .navigation-section -->\n");
      out.write("  </div>\n");
      out.write("  <!-- .container -->\n");
      out.write("</section>\n");
      out.write("<!-- header_section_wrapper -->\n");
      out.write("\n");
      out.write("<section class=\"breadcrumb_section\">\n");
      out.write("    <div class=\"container\">\n");
      out.write("        <div class=\"row\">\n");
      out.write("            <ol class=\"breadcrumb\">\n");
      out.write("                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/front/home\">首页</a></li>\n");
      out.write("                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/conf/showRefreh\">发布会</a></li>\n");
      out.write("            </ol> </div>\n");
      out.write("    </div>\n");
      out.write("</section>\n");
      out.write("<div class=\"container\">\n");
      out.write("<div class=\"row\">\n");
      out.write("<div class=\"col-md-8\">\n");
      out.write("\n");
      out.write("      ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("    <nav aria-label=\"Page navigation\" class=\"pagination_section\">\n");
      out.write("        <ul class=\"pagination\">\n");
      out.write("\t\t\t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/conf/previous\"> <button class=\"active\">上一页</button> </a>\n");
      out.write("            ");
      if (_jspx_meth_c_005fforEach_005f1(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\t\t\t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/conf/next\"> <button class=\"active\">下一页</button> </a>\n");
      out.write("        </ul>\n");
      out.write("    </nav>\n");
      out.write("    <!-- navigation -->\n");
      out.write("</div>\n");
      out.write("<!-- col-md-8 -->\n");
      out.write("<div class=\"col-md-4\">\n");
      out.write("    <div class=\"widget\">\n");
      out.write("        <div class=\"widget_title widget_black\">\n");
      out.write("            <h2><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/news/showRefreh\">新闻</a></h2>\n");
      out.write("        </div>\n");
      out.write("        ");
      if (_jspx_meth_c_005fforEach_005f2(_jspx_page_context))
        return;
      out.write("\n");
      out.write("        <p class=\"widget_divider\"><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/news/showRefreh\" target=\"_self\">更多&#xA0;&#171;</a></p>\n");
      out.write("    </div>\n");
      out.write("    <!-- Popular News -->\n");
      out.write("\n");
      out.write("    <div class=\"widget hidden-xs m30\">\n");
      out.write("        <img class=\"img-responsive adv_img\" src=\"../assets/img/right_add1.jpg\" alt=\"add_one\" />\n");
      out.write("        <img class=\"img-responsive adv_img\" src=\"../assets/img/right_add2.jpg\" alt=\"add_one\" />\n");
      out.write("        <img class=\"img-responsive adv_img\" src=\"../assets/img/right_add3.jpg\" alt=\"add_one\" />\n");
      out.write("        <img class=\"img-responsive adv_img\" src=\"../assets/img/right_add4.jpg\" alt=\"add_one\" />\n");
      out.write("    </div>\n");
      out.write("    <!-- Advertisement -->\n");
      out.write("    <div class=\"widget hidden-xs m30\">\n");
      out.write("        <img class=\"img-responsive widget_img\" src=\"../assets/img/right_add5.jpg\" alt=\"add_one\" />\n");
      out.write("    </div>\n");
      out.write("    <!-- Advertisement -->\n");
      out.write("\n");
      out.write("    <div class=\"widget reviews m30\">\n");
      out.write("        <div class=\"widget_title widget_black\">\n");
      out.write("            <h2><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/video/showRefreh\">视频</a></h2>\n");
      out.write("        </div>\n");
      out.write("        ");
      if (_jspx_meth_c_005fforEach_005f3(_jspx_page_context))
        return;
      out.write("\n");
      out.write("        <p class=\"widget_divider\"><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/video/showRefreh\" target=\"_self\">更多&#xA0;&#171;</a></p>\n");
      out.write("    </div>\n");
      out.write("    <!-- Reviews Videos -->\n");
      out.write("\n");
      out.write("    <div class=\"widget hidden-xs m30\">\n");
      out.write("        <img class=\"img-responsive widget_img\" src=\"../assets/img/right_add6.jpg\" alt=\"add_one\" />\n");
      out.write("    </div>\n");
      out.write("    <!-- Advertisement -->\n");
      out.write("</div>\n");
      out.write("<!-- col-md-4 -->\n");
      out.write("\n");
      out.write("</div>\n");
      out.write("<!-- row -->\n");
      out.write("</div>\n");
      out.write("<!-- container -->\n");
      out.write("</div>\n");
      out.write("<!-- #content-wrapper -->\n");
      out.write("</div>\n");
      out.write("<!-- .offcanvas-pusher -->\n");
      out.write("        <a href=\"#\" class=\"crunchify-top\" style=\"display: block;\"><i class=\"fa fa-angle-up\" aria-hidden=\"true\"></i></a>\n");
      out.write("</div>\n");
      out.write("<!-- #main-wrapper -->\n");
      out.write("<div class=\"footer_bottom_Section\">\n");
      out.write("    <div class=\"container\">\n");
      out.write("        <div class=\"row\">\n");
      out.write("            <div class=\"footer\">\n");
      out.write("                <div class=\"col-sm-3\">\n");
      out.write("                    <div class=\"social\">\n");
      out.write("                        <a class=\"icons-sm fb-ic\"><i class=\"fa fa-facebook\"></i></a>\n");
      out.write("                        <!--Twitter-->\n");
      out.write("                        <a class=\"icons-sm tw-ic\"><i class=\"fa fa-twitter\"></i></a>\n");
      out.write("                        <!--Google +-->\n");
      out.write("                        <a class=\"icons-sm inst-ic\"><i class=\"fa fa-instagram\"> </i></a>\n");
      out.write("                        <!--Linkedin-->\n");
      out.write("                        <a class=\"icons-sm tmb-ic\"><i class=\"fa fa-tumblr\"> </i></a>\n");
      out.write("                        <!--Pinterest-->\n");
      out.write("                        <a class=\"icons-sm rss-ic\"><i class=\"fa fa-rss\"> </i></a>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"col-sm-6\"> <p>Copyright © 2019. Leon .</p></div>\n");
      out.write("                <div class=\"col-sm-3\"> <p>Technology News Magazine</p></div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("<!-- jquery Core-->\n");
      out.write("<script src=\"../assets/js/jquery-2.1.4.min.js\"></script>\n");
      out.write("<!-- Bootstrap -->\n");
      out.write("<script src=\"../assets/js/bootstrap.min.js\"></script>\n");
      out.write("<!-- Theme Menu -->\n");
      out.write("<script src=\"../assets/js/mobile-menu.js\"></script>\n");
      out.write("<!-- Owl carousel -->\n");
      out.write("<script src=\"../assets/js/owl.carousel.min.js\"></script>\n");
      out.write("<!-- Theme Script -->\n");
      out.write("<script src=\"../assets/js/script.js\"></script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fstep_005fend_005fbegin.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f0.setParent(null);
    // /web_front/conference/conferences.jsp(144,6) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setVar("i");
    // /web_front/conference/conferences.jsp(144,6) name = begin type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setBegin(0);
    // /web_front/conference/conferences.jsp(144,6) name = end type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setEnd(((java.lang.Integer) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${conf.num-1}", int.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).intValue());
    // /web_front/conference/conferences.jsp(144,6) name = step type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setStep(1);
    int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
      if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("        <div class=\"entity_wrapper\">\n");
          out.write("            <div class=\"entity_title\">\n");
          out.write("                <h1><a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("/conf/showConference?id=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${conf.getNow(i).id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write('"');
          out.write('>');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${conf.getNow(i).name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("</a></h1>\n");
          out.write("            </div>\n");
          out.write("            <!-- entity_title -->\n");
          out.write("            <div class=\"entity_meta\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${conf.getNow(i).date}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write(" , by: ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${conf.getNow(i).author}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("</div>\n");
          out.write("            <!-- entity_meta -->\n");
          out.write("            <div class=\"rating\">\n");
          out.write("                <i class=\"fa fa-star\"></i><i class=\"fa fa-star\"></i><i class=\"fa fa-star\"></i><i class=\"fa fa-star\"></i>\n");
          out.write("                <i class=\"fa fa-star-half-full\"></i>\n");
          out.write("            </div>\n");
          out.write("            <!-- rating -->\n");
          out.write("            <div class=\"entity_social\">\n");
          out.write("                <a href=\"#\" class=\"icons-sm sh-ic\"><i class=\"fa fa-share-alt\"></i><b>424</b><span class=\"share_ic\">Shares</span></a>\n");
          out.write("                <a href=\"#\" class=\"icons-sm fb-ic\"><i class=\"fa fa-facebook\"></i></a>\n");
          out.write("                <a href=\"#\" class=\"icons-sm tw-ic\"><i class=\"fa fa-twitter\"></i></a>\n");
          out.write("                <a href=\"#\" class=\"icons-sm inst-ic\"><i class=\"fa fa-google-plus\"> </i></a>\n");
          out.write("                <a href=\"#\" class=\"icons-sm tmb-ic\"><i class=\"fa fa-ge\"> </i></a>\n");
          out.write("                <a href=\"#\" class=\"icons-sm rss-ic\"><i class=\"fa fa-rss\"> </i></a>\n");
          out.write("                <span class=\"arrow\">&#187;</span>\n");
          out.write("            </div>                     \n");
          out.write("            <!-- entity_social -->\n");
          out.write("            <div class=\"entity_thumb\">\n");
          out.write("                <a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("/conf/showConference?id=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${conf.getNow(i).id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("\">\n");
          out.write("                    <img class=\"img-responsive\" src=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${conf.getNow(i).poster}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("\" alt=\"feature-top\"/>\n");
          out.write("                </a>\n");
          out.write("            </div>\n");
          out.write("            <div class=\"entity_content\">\n");
          out.write("                <a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("/conf/showConference?id=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${conf.getNow(i).id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("\"><p>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${conf.getNow(i).sketch}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("</p></a>\n");
          out.write("            </div>\n");
          out.write("        </div>\n");
          out.write("        <br/>\n");
          out.write("    ");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f0.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fstep_005fend_005fbegin.reuse(_jspx_th_c_005fforEach_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f1.setParent(null);
    // /web_front/conference/conferences.jsp(181,12) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f1.setVar("i");
    // /web_front/conference/conferences.jsp(181,12) name = begin type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f1.setBegin(1);
    // /web_front/conference/conferences.jsp(181,12) name = end type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f1.setEnd(((java.lang.Integer) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${conf.page_num}", int.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).intValue());
    int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
      if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("\t\t\t\t<a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("/conf/jumpTo?id=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${i}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("\"> <button>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${i}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("</button> </a>&nbsp;\n");
          out.write("            ");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f1.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin.reuse(_jspx_th_c_005fforEach_005f1);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f2 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f2.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f2.setParent(null);
    // /web_front/conference/conferences.jsp(195,8) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f2.setVar("i");
    // /web_front/conference/conferences.jsp(195,8) name = begin type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f2.setBegin(0);
    // /web_front/conference/conferences.jsp(195,8) name = end type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f2.setEnd(3);
    int[] _jspx_push_body_count_c_005fforEach_005f2 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f2 = _jspx_th_c_005fforEach_005f2.doStartTag();
      if (_jspx_eval_c_005fforEach_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("            <div class=\"media\">\n");
          out.write("                <div class=\"media-left\">\n");
          out.write("                    <a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("/news/showNews?id=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${news.getNow(i).id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("\" target=\"_self\">\n");
          out.write("                        <img class=\"media-object\" src=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${news.getNow(i).image}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("\" alt=\"Generic placeholder image\" width=\"150\" height=\"100\" /></a>\n");
          out.write("                </div>\n");
          out.write("                <div class=\"media-body\">\n");
          out.write("                    <h3 class=\"media-heading\">\n");
          out.write("                        <a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("/news/showNews?id=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${news.getNow(i).id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("\" target=\"_self\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${news.getNow(i).title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("</a>\n");
          out.write("                    </h3>\n");
          out.write("                    <span class=\"media-date\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${news.getNow(i).date}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write(" , by: ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${news.getNow(i).author}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("</span>\n");
          out.write("                    <div class=\"widget_article_social\">\n");
          out.write("                        <span><a href=\"#\" target=\"_self\"> <i class=\"fa fa-share-alt\"></i>424</a> Shares</span> \n");
          out.write("                        <span><a href=\"#\" target=\"_self\"><i class=\"fa fa-comments-o\"></i>4</a> Comments</span>\n");
          out.write("                    </div>\n");
          out.write("                </div>\n");
          out.write("            </div>\n");
          out.write("        ");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f2[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f2.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f2.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin.reuse(_jspx_th_c_005fforEach_005f2);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f3 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f3.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f3.setParent(null);
    // /web_front/conference/conferences.jsp(233,8) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f3.setVar("i");
    // /web_front/conference/conferences.jsp(233,8) name = begin type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f3.setBegin(0);
    // /web_front/conference/conferences.jsp(233,8) name = end type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f3.setEnd(3);
    int[] _jspx_push_body_count_c_005fforEach_005f3 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f3 = _jspx_th_c_005fforEach_005f3.doStartTag();
      if (_jspx_eval_c_005fforEach_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("            <div class=\"media\">\n");
          out.write("                <div class=\"media-left\">\n");
          out.write("                    <a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("/video/showVideo?id=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${video.getTop(i).id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("\" target=\"_self\">\n");
          out.write("                        <img class=\"media-object\" src=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${video.getTop(i).image}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("\" alt=\"Generic placeholder image\" width=\"150\" height=\"100\" /></a>\n");
          out.write("                </div>\n");
          out.write("                <div class=\"media-body\">\n");
          out.write("                    <h3 class=\"media-heading\">\n");
          out.write("                        <a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("/video/showVideo?id=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${video.getTop(i).id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("\" target=\"_self\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${video.getTop(i).title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("</a>\n");
          out.write("                    </h3> \n");
          out.write("                    <span class=\"rating\">\n");
          out.write("                        <i class=\"fa fa-star\"></i><i class=\"fa fa-star\"></i><i class=\"fa fa-star\"></i><i class=\"fa fa-star\"></i><i class=\"fa fa-star-half-full\"></i>\n");
          out.write("                    </span>\n");
          out.write("                    <br/><span class=\"media-date\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${video.getTop(i).date}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write(" , by: ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${video.getTop(i).author}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("</span>\n");
          out.write("                </div>\n");
          out.write("            </div>\n");
          out.write("        ");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f3[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f3.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f3.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin.reuse(_jspx_th_c_005fforEach_005f3);
    }
    return false;
  }
}
