package com.Leon.pojo;
// Generated 2019-1-2 0:12:42 by Hibernate Tools 4.3.1

import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name = "users", catalog = "cms")
public class Users implements java.io.Serializable {

	private String name;
	private String password;
	private String mail;
	private String phone;
	private String image;

	private List<Users> all = new ArrayList<>();

	public Users() {
	}

	public Users(String name, String password) {
		this.name = name;
		this.password = password;
	}

	public Users(String name, String password, String mail, String phone, String image) {
		this.name = name;
		this.password = password;
		this.mail = mail;
		this.phone = phone;
		this.image = image;
	}

	public void setInfo(String name, String password, String mail, String phone, String image) {
		this.name = name;
		this.password = password;
		this.mail = mail;
		this.phone = phone;
		this.image = image;
	}

	public void setAll(List<Users> all) {
		this.all = all;
	}

	@Id
	@Column(name = "name", unique = true, nullable = false, length = 16)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "password", nullable = false, length = 16)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "mail", length = 20)
	public String getMail() {
		return this.mail;
	}

	public void setMail(String mail) {
		this.mail = mail;
	}

	@Column(name = "phone", length = 16)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "image", length = 128)
	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	@Override
	public String toString() {
		return name + " " + password;
	}

}
