/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.0-RC5
 * Generated at: 2020-01-02 13:06:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.web_005fback;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class back_005findex_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    <title>TECH-后台管理</title>\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"/>\n");
      out.write("    <meta charset=\"utf-8\"/>\n");
      out.write("\t<meta name=\"renderer\" content=\"webkit\"/>\n");
      out.write("\t<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\"/>\n");
      out.write("\t<meta http-equiv=\"Access-Control-Allow-Origin\" content=\"*\"/>\n");
      out.write("\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, maximum-scale=1\"/>\n");
      out.write("\t<meta name=\"apple-mobile-web-app-status-bar-style\" content=\"black\"/>\n");
      out.write("\t<meta name=\"apple-mobile-web-app-capable\" content=\"yes\"/>\n");
      out.write("\t<meta name=\"format-detection\" content=\"telephone=no\"/>\n");
      out.write("\t<link rel=\"icon\" href=\"favicon.ico\"/>\n");
      out.write("\t<link rel=\"stylesheet\" href=\"layui/css/layui.css\" media=\"all\" />\n");
      out.write("\t<link rel=\"stylesheet\" href=\"//at.alicdn.com/t/font_eolqem241z66flxr.css\" media=\"all\" />\n");
      out.write("\t<link rel=\"stylesheet\" href=\"css/main.css\" media=\"all\" />\n");
      out.write("    </head>\n");
      out.write("<body class=\"main_body\">\n");
      out.write("\t<div class=\"layui-layout layui-layout-admin\">\n");
      out.write("\t\t<!-- 顶部 -->\n");
      out.write("        <div class=\"layui-header header\">\n");
      out.write("\t\t\t<div class=\"layui-main\">\n");
      out.write("\t\t\t\t<a href=\"#\" class=\"logo\">TECH 后台管理</a>\n");
      out.write("\t\t\t\t<!-- 搜索 -->\n");
      out.write("\t\t\t\t<div class=\"layui-form component\">\n");
      out.write("\t\t\t        <select name=\"modules\" lay-verify=\"required\" lay-search=\"\">\n");
      out.write("\t\t\t\t\t\t<option value=\"\">直接选择或搜索选择</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"1\">layer</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"2\">form</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"3\">layim</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"4\">element</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"5\">laytpl</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"6\">upload</option>\n");
      out.write("\t\t\t        </select>\n");
      out.write("\t\t\t        <i class=\"layui-icon\">&#xe615;</i>\n");
      out.write("\t\t\t    </div>\n");
      out.write("\t\t\t    <!-- 天气信息 -->\n");
      out.write("\t\t\t    <div class=\"weather\" pc=\"\">\n");
      out.write("\t\t\t    \t<div id=\"tp-weather-widget\"></div>\n");
      out.write("\t\t\t\t\t<script>(function(T,h,i,n,k,P,a,g,e){g=function(){P=h.createElement(i);a=h.getElementsByTagName(i)[0];P.src=k;P.charset=\"utf-8\";P.async=1;a.parentNode.insertBefore(P,a)};T[\"ThinkPageWeatherWidgetObject\"]=n;T[n]||(T[n]=function(){(T[n].q=T[n].q||[]).push(arguments)});T[n].l=+new Date();if(T.attachEvent){T.attachEvent(\"onload\",g)}else{T.addEventListener(\"load\",g,false)}}(window,document,\"script\",\"tpwidget\",\"//widget.seniverse.com/widget/chameleon.js\"))</script>\n");
      out.write("\t\t\t\t\t<script>tpwidget(\"init\", {\n");
      out.write("\t\t\t\t\t    \"flavor\": \"slim\",\n");
      out.write("\t\t\t\t\t    \"location\": \"WX4FBXXFKE4F\",\n");
      out.write("\t\t\t\t\t    \"geolocation\": \"disabled\",\n");
      out.write("\t\t\t\t\t    \"language\": \"zh-chs\",\n");
      out.write("\t\t\t\t\t    \"unit\": \"c\",\n");
      out.write("\t\t\t\t\t    \"theme\": \"chameleon\",\n");
      out.write("\t\t\t\t\t    \"container\": \"tp-weather-widget\",\n");
      out.write("\t\t\t\t\t    \"bubble\": \"disabled\",\n");
      out.write("\t\t\t\t\t    \"alarmType\": \"badge\",\n");
      out.write("\t\t\t\t\t    \"color\": \"#FFFFFF\",\n");
      out.write("\t\t\t\t\t    \"uid\": \"U9EC08A15F\",\n");
      out.write("\t\t\t\t\t    \"hash\": \"14dff75e7253d3a8b9727522759f3455\"\n");
      out.write("\t\t\t\t\t});\n");
      out.write("\t\t\t\t\ttpwidget(\"show\");</script>\n");
      out.write("\t\t\t    </div>\n");
      out.write("\t\t\t    <!-- 顶部右侧菜单 -->\n");
      out.write("\t\t\t    <ul class=\"layui-nav top_menu\">\n");
      out.write("                    <li class=\"layui-nav-item lockcms\" pc=\"\">\n");
      out.write("                            <a href=\"javascript:;\"><i class=\"iconfont icon-lock1\"></i><cite>锁屏</cite></a>\n");
      out.write("                    </li>\n");
      out.write("                    <li class=\"layui-nav-item\" pc=\"\">\n");
      out.write("                            <a href=\"javascript:;\">\n");
      out.write("                                <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${admin.image}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" class=\"layui-circle\" width=\"35\" height=\"35\"/>\n");
      out.write("                                <cite>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${admin.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</cite>\n");
      out.write("                            </a>\n");
      out.write("                            <dl class=\"layui-nav-child\">\n");
      out.write("                                <dd><a href=\"javascript:;\" data-url=\"page/user/userInfo.xhtml\"><i class=\"iconfont icon-zhanghu\" data-icon=\"icon-zhanghu\"></i><cite>个人资料</cite></a></dd>\n");
      out.write("                                <dd><a href=\"javascript:;\" data-url=\"page/user/changePwd.html\"><i class=\"iconfont icon-shezhi1\" data-icon=\"icon-shezhi1\"></i><cite>修改密码</cite></a></dd>\n");
      out.write("                                <dd>\n");
      out.write("                                    <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/front/logout\"><i class=\"iconfont icon-loginout\"></i><cite>退出</cite></a>\n");
      out.write("                                </dd>\n");
      out.write("                            </dl>\n");
      out.write("                    </li>\n");
      out.write("                </ul>\n");
      out.write("\t\t\t</div>\n");
      out.write("        </div>\n");
      out.write("\t\t<!-- 左侧导航 -->\n");
      out.write("\t\t<div class=\"layui-side layui-bg-black\">\n");
      out.write("\t\t\t<div class=\"user-photo\">\n");
      out.write("\t\t\t\t<a class=\"img\" title=\"我的头像\" ><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${admin.image}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"/></a>\n");
      out.write("\t\t\t\t<p>你好！<span class=\"userName\">Leon</span>, 欢迎回来</p>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"navBar layui-side-scroll\"></div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<!-- 右侧内容 -->\n");
      out.write("\t\t<div class=\"layui-body layui-form\">\n");
      out.write("\t\t\t<div class=\"layui-tab marg0\" lay-filter=\"bodyTab\">\n");
      out.write("\t\t\t\t<ul class=\"layui-tab-title top_tab\">\n");
      out.write("\t\t\t\t\t<li class=\"layui-this\" lay-id=\"\"><i class=\"iconfont icon-computer\"></i> <cite>后台首页</cite></li>\n");
      out.write("\t\t\t\t</ul>\n");
      out.write("\t\t\t\t<div class=\"layui-tab-content clildFrame\">\n");
      out.write("\t\t\t\t\t<div class=\"layui-tab-item layui-show\">\n");
      out.write("\t\t\t\t\t\t<iframe src=\"page/main.html\"></iframe>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<!-- 底部 -->\n");
      out.write("\t\t<div class=\"layui-footer footer\">\n");
      out.write("            <p>copyright @2019 Leon</p>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\n");
      out.write("\t<!-- 锁屏 -->\n");
      out.write("\t<div class=\"admin-header-lock\" id=\"lock-box\" style=\"display: none;\">\n");
      out.write("\t\t<div class=\"admin-header-lock-img\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${admin.image}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"/></div>\n");
      out.write("\t\t<div class=\"admin-header-lock-name\" id=\"lockUserName\">Leon</div>\n");
      out.write("\t\t<div class=\"input_btn\">\n");
      out.write("\t\t\t<input type=\"password\" class=\"admin-header-lock-input layui-input\" placeholder=\"请输入密码解锁..\" name=\"lockPwd\" id=\"lockPwd\" />\n");
      out.write("\t\t\t<button class=\"layui-btn\" id=\"unlock\">解锁</button>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\t<!-- 移动导航 -->\n");
      out.write("\t<div class=\"site-tree-mobile layui-hide\"><i class=\"layui-icon\">&#xe602;</i></div>\n");
      out.write("\t<div class=\"site-mobile-shade\"></div>\n");
      out.write("\n");
      out.write("\t<script type=\"text/javascript\" src=\"layui/layui.js\"></script>\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/nav.js\"></script>\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/leftNav.js\"></script>\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/index.js\"></script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
