/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.0-RC5
 * Generated at: 2020-01-02 12:50:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.web_005ffront;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class front_005findex_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\"/>\r\n");
      out.write("<title>TECH-首页</title>\r\n");
      out.write("    <!-- favicon -->\r\n");
      out.write("    <link href=\"assets/img/favicon.png\" rel=\"icon\" />\r\n");
      out.write("    <!-- web-fonts -->\r\n");
      out.write("    <link href='https://fonts.googleapis.com/css?family=Roboto:100,300,400,700,500' rel='stylesheet' type='text/css' />\r\n");
      out.write("    <!-- Bootstrap -->\r\n");
      out.write("    <link href=\"assets/css/bootstrap.min.css\" rel=\"stylesheet\" />\r\n");
      out.write("    <!-- font-awesome -->\r\n");
      out.write("    <link href=\"assets/fonts/font-awesome/font-awesome.min.css\" rel=\"stylesheet\" />\r\n");
      out.write("    <!-- Mobile Menu Style -->\r\n");
      out.write("    <link href=\"assets/css/mobile-menu.css\" rel=\"stylesheet\" />\r\n");
      out.write("    <!-- Owl carousel -->\r\n");
      out.write("    <link href=\"assets/css/owl.carousel.css\" rel=\"stylesheet\" />\r\n");
      out.write("    <link href=\"assets/css/owl.theme.default.min.css\" rel=\"stylesheet\" />\r\n");
      out.write("    <!-- Theme Style -->\r\n");
      out.write("    <link href=\"assets/css/style.css\" rel=\"stylesheet\" />\r\n");
      out.write("</head>\r\n");
      out.write("    \r\n");
      out.write("<body id=\"page-top\" data-spy=\"scroll\" data-target=\".navbar\">\r\n");
      out.write("    <div id=\"main-wrapper\">\r\n");
      out.write("    <!-- Page Preloader -->\r\n");
      out.write("    <div id=\"preloader\"><div id=\"status\"><div class=\"status-mes\"></div></div></div>\r\n");
      out.write("    <!-- preloader -->\r\n");
      out.write("    <div class=\"uc-mobile-menu-pusher\">\r\n");
      out.write("    <div class=\"content-wrapper\">\r\n");
      out.write("    <section id=\"header_section_wrapper\" class=\"header_section_wrapper\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"header-section\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-md-4\">\r\n");
      out.write("                        <div class=\"left_section\">\r\n");
      out.write("\r\n");
      out.write("                            <span class=\"date\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${util.getDateTime() }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</span>\r\n");
      out.write("                            <!-- Date -->\r\n");
      out.write("                            <div class=\"social\">\r\n");
      out.write("                                <a class=\"icons-sm fb-ic\"><i class=\"fa fa-facebook\"></i></a>\r\n");
      out.write("                                <!--Twitter-->\r\n");
      out.write("                                <a class=\"icons-sm tw-ic\"><i class=\"fa fa-twitter\"></i></a>\r\n");
      out.write("                                <!--Google +-->\r\n");
      out.write("                                <a class=\"icons-sm inst-ic\"><i class=\"fa fa-instagram\"> </i></a>\r\n");
      out.write("                                <!--Linkedin-->\r\n");
      out.write("                                <a class=\"icons-sm tmb-ic\"><i class=\"fa fa-tumblr\"> </i></a>\r\n");
      out.write("                                <!--Pinterest-->\r\n");
      out.write("                                <a class=\"icons-sm rss-ic\"><i class=\"fa fa-rss\"> </i></a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <!-- Top Social Section -->\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <!-- Left Header Section -->\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-md-4\">\r\n");
      out.write("                        <div class=\"logo\">\r\n");
      out.write("                            <a href=\"#\"><img src=\"assets/img/logo.png\" alt=\"Tech NewsLogo\" /></a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <!-- Logo Section -->\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-md-4\">\r\n");
      out.write("                        <div class=\"right_section\">\r\n");
      out.write("                            <ul class=\"nav navbar-nav\">\r\n");
      out.write("\t\r\n");
      out.write("                                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/login.jsp\">Login</a></li>\r\n");
      out.write("                                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/login.jsp\">Register</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                            <!-- LogAndReg Section -->\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <!-- Right Header Section -->\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <!-- Header Section -->\r\n");
      out.write("            <div class=\"navigation-section\">\r\n");
      out.write("                <nav class=\"navbar m-menu navbar-default\">\r\n");
      out.write("                    <div class=\"container\">\r\n");
      out.write("                        <div class=\"collapse navbar-collapse\" id=\"#navbar-collapse-1\">\r\n");
      out.write("                            <ul class=\"nav navbar-nav main-nav\">\r\n");
      out.write("                                <li>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</li>\r\n");
      out.write("                                <!--<li class=\"active\"><a>首页</a></li>-->\r\n");
      out.write("\r\n");
      out.write("                                <li class=\"active\"><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/front/home\">首页</a></li>\r\n");
      out.write("                                <li>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</li>\r\n");
      out.write("                                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/conf/showRefreh\">发布会</a></li>\r\n");
      out.write("                                <li>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</li>\r\n");
      out.write("                                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/news/showRefreh\">新闻</a></li>\r\n");
      out.write("                                <li>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</li>\r\n");
      out.write("                                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/video/showRefreh\">视频</a></li>\r\n");
      out.write("                                <li>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</li>\r\n");
      out.write("                                <li class=\"dropdown m-menu-fw\">\r\n");
      out.write("                                    <a href=\"#\" data-toggle=\"dropdown\" class=\"dropdown-toggle\">产品               \r\n");
      out.write("                                    <span><i class=\"fa fa-angle-down\"></i></span></a>\r\n");
      out.write("                                    <ul class=\"dropdown-menu\"> \t<li>\r\n");
      out.write("\r\n");
      out.write("                                        <div class=\"m-menu-content\">\r\n");
      out.write("                                            <span><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/product/showProducts?type=phone\"  class=\"dropdown-header\">手机</a></span>&nbsp;\r\n");
      out.write("                                            <span><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/product/showProducts?type=computer\"  class=\"dropdown-header\">电脑</a></span>&nbsp;\r\n");
      out.write("                                            <span><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/product/showProducts?type=other\"  class=\"dropdown-header\">其他</a></span>&nbsp;\r\n");
      out.write("                                        </div></li>\r\n");
      out.write("                                    </ul></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <!-- .navbar-collapse -->\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- .container -->\r\n");
      out.write("                </nav>\r\n");
      out.write("                <!-- .nav -->\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- .navigation-section -->\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- .container -->\r\n");
      out.write("    </section>\r\n");
      out.write("    <!-- header_section_wrapper -->\r\n");
      out.write("\r\n");
      out.write("    <section id=\"feature_news_section\" class=\"feature_news_section\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-md-7\">\r\n");
      out.write("                    <div class=\"feature_article_wrapper\">\r\n");
      out.write("                        <div class=\"feature_article_img\">\r\n");
      out.write("\r\n");
      out.write("                            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${conf.top.poster}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" class=\"img-responsive top_static_article_img\" width=\"955\" height=\"832\"/>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <!-- feature_article_img -->\r\n");
      out.write("                        <div class=\"feature_article_inner\">\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"tag_lg red\"><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/conf/showRefreh\">发布会</a></div>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"feature_article_title\">\r\n");
      out.write("                                <h1><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/conf/showConference?id=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${conf.top.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write('"');
      out.write('>');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${conf.top.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</a></h1>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <!-- feature_article_title -->\r\n");
      out.write("                            <div class=\"feature_article_date\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${conf.top.address}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write(' ');
      out.write(',');
      out.write(' ');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${conf.top.date}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</div>\r\n");
      out.write("                            <!-- feature_article_date -->\r\n");
      out.write("                            <div class=\"feature_article_content\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${conf.top.sketch}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</div>\r\n");
      out.write("                            <!-- feature_article_content -->\r\n");
      out.write("                            <div class=\"article_social\">\r\n");
      out.write("                                <span><i class=\"fa fa-share-alt\"></i><a href=\"#\">424</a>分享</span>\r\n");
      out.write("                                <span><i class=\"fa fa-comments-o\"></i><a href=\"#\">4</a>评论</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <!-- article_social -->\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <!-- feature_article_inner -->\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- feature_article_wrapper -->\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- col-md-7 -->\r\n");
      out.write("                <div class=\"col-md-5\">\r\n");
      out.write("                    <div class=\"feature_static_wrapper\">\r\n");
      out.write("                        <div class=\"feature_article_img\">\r\n");
      out.write("\r\n");
      out.write("                            <img class=\"img-responsive\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${news.top.image}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" alt=\"feature-top\" width=\"670\" height=\"395\"/>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <!-- feature_article_img -->\r\n");
      out.write("                        <div class=\r\n");
      out.write("                        \"feature_article_inner\">\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"tag_lg purple\"><a href=\"#\">新闻</a></div>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"feature_article_title\">\r\n");
      out.write("                                <h1><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/news/showNews?id=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${news.top.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write('"');
      out.write('>');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${news.top.title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</a></h1>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <!-- feature_article_title -->\r\n");
      out.write("                            <div class=\"feature_article_date\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${news.top.author}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write(' ');
      out.write(',');
      out.write(' ');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${news.top.date}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</div>\r\n");
      out.write("                            <!-- feature_article_date -->\r\n");
      out.write("                            <div class=\"feature_article_content\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${news.top.sketch}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</div>\r\n");
      out.write("                            <!-- feature_article_content -->\r\n");
      out.write("                            <div class=\"article_social\">\r\n");
      out.write("                                <span><i class=\"fa fa-share-alt\"></i><a href=\"#\">424</a>分享</span>\r\n");
      out.write("                                <span><i class=\"fa fa-comments-o\"></i><a href=\"#\">4</a>评论</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <!-- article_social -->\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <!-- feature_article_inner -->\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- feature_static_wrapper -->\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- col-md-5 -->\r\n");
      out.write("                <div class=\"col-md-5\">\r\n");
      out.write("                    <div class=\"feature_static_last_wrapper\">\r\n");
      out.write("                        <div class=\"feature_article_img\">\r\n");
      out.write("\r\n");
      out.write("                            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${video.top.image}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" class=\"img-responsive\" alt=\"feature-top\" width=\"670\" height=\"395\" />\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <!-- feature_article_img -->\r\n");
      out.write("                        <div class=\"feature_article_inner\">\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"tag_lg blue\"><a href=\"videos.xhtml\">视频</a></div>\r\n");
      out.write("                            <div class=\"feature_article_title\">\r\n");
      out.write("\r\n");
      out.write("                                <h1><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/video/showVideo?id=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${video.top.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write('"');
      out.write('>');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${video.top.title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</a></h1>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <!-- feature_article_title -->\r\n");
      out.write("                            <div class=\"feature_article_date\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${news.top.author}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write(' ');
      out.write(',');
      out.write(' ');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${news.top.date}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</div>\r\n");
      out.write("                            <!-- feature_article_date -->\r\n");
      out.write("                            <div class=\"feature_article_content\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${video.top.sketch}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <!-- feature_article_content -->\r\n");
      out.write("                            <div class=\"article_social\">\r\n");
      out.write("                                <span><i class=\"fa fa-share-alt\"></i><a href=\"#\">424</a>分享</span>\r\n");
      out.write("                                <span><i class=\"fa fa-comments-o\"></i><a href=\"#\">4</a>评论</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <!-- article_social -->\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <!-- feature_article_inner -->\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- feature_static_wrapper -->\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- col-md-5 -->\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- Row -->\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- container -->\r\n");
      out.write("    </section>\r\n");
      out.write("    <!-- Feature News Section -->\r\n");
      out.write("\r\n");
      out.write("        <section id=\"category_section\" class=\"category_section\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("              <div class=\"row\">\r\n");
      out.write("              <div class=\"col-md-8\">\r\n");
      out.write("                      <div class=\"category_section mobile\">\r\n");
      out.write("                          <div class=\"article_title header_purple\">\r\n");
      out.write("\r\n");
      out.write("                              <h2><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/product/showProducts?type=phone\" target=\"_self\">手机</a></h2>\r\n");
      out.write("                              \r\n");
      out.write("                          </div>\r\n");
      out.write("                          <!-- article_title -->\r\n");
      out.write("                          <div class=\"category_article_wrapper\">\r\n");
      out.write("                              <div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("                              ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                              </div>\r\n");
      out.write("                              <!-- row -->\r\n");
      out.write("                          </div>\r\n");
      out.write("\r\n");
      out.write("                          <p class=\"divider\"><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/product/showProducts?type=phone\">更多&#xA0;&#171;</a></p>\r\n");
      out.write("                          </div>\r\n");
      out.write("                          <!-- Phone Section -->\r\n");
      out.write("\r\n");
      out.write("                      <div class=\"category_section tablet\">\r\n");
      out.write("                          <div class=\"article_title header_pink\">\r\n");
      out.write("\r\n");
      out.write("                              <h2><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/product/showProducts?type=computer\" target=\"_self\">电脑</a></h2>\r\n");
      out.write("                          </div>\r\n");
      out.write("                          <!-- Mobile News Section -->\r\n");
      out.write("\r\n");
      out.write("                          <div class=\"category_article_wrapper\">\r\n");
      out.write("                              <div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("                                  ");
      if (_jspx_meth_c_005fforEach_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                              </div>\r\n");
      out.write("                              <!-- row -->\r\n");
      out.write("                          </div>\r\n");
      out.write("                          <!-- category_article_wrapper -->\r\n");
      out.write("\r\n");
      out.write("                          <p class=\"divider\"><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/product/showProducts?type=computer\">更多&#xA0;&#171;</a></p>\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <!-- Computers Section -->\r\n");
      out.write("\r\n");
      out.write("                      <div class=\"category_section gadget\">\r\n");
      out.write("                          <div class=\"article_title header_black\">\r\n");
      out.write("\r\n");
      out.write("                              <h2><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/product/showProducts?type=other\" target=\"_self\">其他</a></h2>\r\n");
      out.write("                          </div>\r\n");
      out.write("                          <div class=\"category_article_wrapper\">\r\n");
      out.write("                              <div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("                                  ");
      if (_jspx_meth_c_005fforEach_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                              </div>\r\n");
      out.write("                              <!-- row -->\r\n");
      out.write("                          </div>\r\n");
      out.write("                          <div>\r\n");
      out.write("                          <!-- category_article_title -->\r\n");
      out.write("                          <!-- category_article_wrapper -->\r\n");
      out.write("\r\n");
      out.write("                          <p class=\"divider\"><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/product/showProducts?type=other\">更多&#xA0;&#171;</a></p>\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <!-- Gadget News Section -->\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <!-- Others Section -->\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- Left Section -->\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-md-4\">\r\n");
      out.write("                    <div class=\"widget\">\r\n");
      out.write("                        <div class=\"widget_title widget_black\">\r\n");
      out.write("\r\n");
      out.write("                            <h2><a href=\"newss\">新闻</a></h2>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        ");
      if (_jspx_meth_c_005fforEach_005f3(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("                        <p class=\"widget_divider\"><a href=\"newss\" target=\"_self\">更多&#xA0;&#171;</a></p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- Popular News -->\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"widget hidden-xs m30\">\r\n");
      out.write("                        <img class=\"img-responsive adv_img\" src=\"assets/img/right_add1.jpg\" alt=\"add_one\" />\r\n");
      out.write("                        <img class=\"img-responsive adv_img\" src=\"assets/img/right_add2.jpg\" alt=\"add_one\" />\r\n");
      out.write("                        <img class=\"img-responsive adv_img\" src=\"assets/img/right_add3.jpg\" alt=\"add_one\" />\r\n");
      out.write("                        <img class=\"img-responsive adv_img\" src=\"assets/img/right_add4.jpg\" alt=\"add_one\" />\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- Advertisement -->\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"widget hidden-xs m30\">\r\n");
      out.write("                        <img class=\"img-responsive widget_img\" src=\"assets/img/right_add5.jpg\" alt=\"add_one\" />\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- Advertisement -->\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"widget reviews m30\">\r\n");
      out.write("                            <div class=\"widget_title widget_black\">\r\n");
      out.write("\r\n");
      out.write("                                <h2><a href=\"videos\">视频</a></h2>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            ");
      if (_jspx_meth_c_005fforEach_005f4(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("                            <p class=\"widget_divider\"><a href=\"videos\" target=\"_self\">更多&#xA0;&#171;</a></p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                <!-- Reviews Videos -->\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- Right Section -->\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- Row -->\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- Container -->\r\n");
      out.write("        </section>\r\n");
      out.write("        <!-- Category News Section -->\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- #content-wrapper -->\r\n");
      out.write("    </div>\r\n");
      out.write("<!-- .offcanvas-pusher -->\r\n");
      out.write("    <a href=\"#\" class=\"crunchify-top\" style=\"display: block;\"><i class=\"fa fa-angle-up\" aria-hidden=\"true\"></i></a>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- #main-wrapper -->\r\n");
      out.write("\r\n");
      out.write("    <div class=\"footer_bottom_Section\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"footer\">\r\n");
      out.write("                    <div class=\"col-sm-3\">\r\n");
      out.write("                        <div class=\"social\">\r\n");
      out.write("                            <a class=\"icons-sm fb-ic\"><i class=\"fa fa-facebook\"></i></a>\r\n");
      out.write("                            <!--Twitter-->\r\n");
      out.write("                            <a class=\"icons-sm tw-ic\"><i class=\"fa fa-twitter\"></i></a>\r\n");
      out.write("                            <!--Google +-->\r\n");
      out.write("                            <a class=\"icons-sm inst-ic\"><i class=\"fa fa-instagram\"> </i></a>\r\n");
      out.write("                            <!--Linkedin-->\r\n");
      out.write("                            <a class=\"icons-sm tmb-ic\"><i class=\"fa fa-tumblr\"> </i></a>\r\n");
      out.write("                            <!--Pinterest-->\r\n");
      out.write("                            <a class=\"icons-sm rss-ic\"><i class=\"fa fa-rss\"> </i></a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-sm-6\"> <p>Copyright © 2019. Leon .</p></div>\r\n");
      out.write("                    <div class=\"col-sm-3\"> <p>Technology News Magazine</p></div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- jquery Core-->\r\n");
      out.write("    <script src=\"assets/js/jquery-2.1.4.min.js\"></script>\r\n");
      out.write("    <!-- Bootstrap -->\r\n");
      out.write("    <script src=\"assets/js/bootstrap.min.js\"></script>\r\n");
      out.write("    <!-- Theme Menu -->\r\n");
      out.write("    <script src=\"assets/js/mobile-menu.js\"></script>\r\n");
      out.write("    <!-- Owl carousel -->\r\n");
      out.write("    <script src=\"assets/js/owl.carousel.min.js\"></script>\r\n");
      out.write("    <!-- Theme Script -->\r\n");
      out.write("    <script src=\"assets/js/script.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f0.setParent(null);
    // /web_front/front_index.jsp(236,30) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setVar("i");
    // /web_front/front_index.jsp(236,30) name = begin type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setBegin(0);
    // /web_front/front_index.jsp(236,30) name = end type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setEnd(1);
    int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
      if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                                  <div class=\"col-md-6\">\r\n");
          out.write("                                      <div class=\"category_article_body\">\r\n");
          out.write("                                          <div class=\"top_article_img\">\r\n");
          out.write("                                              <a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("/product/showProduct?id=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.getTop_phone(i).id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("\" target=\"_self\">\r\n");
          out.write("                                                  <img class=\"img-responsive\" src=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.getTop_phone(i).image}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("\" alt=\"feature-top\" height=\"700\" width=\"520\"/>\r\n");
          out.write("                                              </a>\r\n");
          out.write("                                          </div>\r\n");
          out.write("                                          <!-- top_article_img -->\r\n");
          out.write("                                          <span class=\"tag pink\">热销</span>\r\n");
          out.write("\r\n");
          out.write("                                          <div class=\"category_article_title\">\r\n");
          out.write("                                              <h2><a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("/product/showProduct?id=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.getTop_phone(i).id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("\" target=\"_self\">\r\n");
          out.write("                                                      ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.getTop_phone(i).name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("</a></h2>\r\n");
          out.write("                                          </div>\r\n");
          out.write("                                          <!-- category_article_title -->\r\n");
          out.write("                                          <div class=\"article_date\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.getTop_phone(i).date}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write(" , by: ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.getTop_phone(i).brand}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("</div>\r\n");
          out.write("                                          <!--article_date-->\r\n");
          out.write("                                          <div class=\"category_article_content\"> ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.getTop_phone(i).sketch}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write(" </div>\r\n");
          out.write("                                          <!-- category_article_content -->\r\n");
          out.write("                                          <div class=\"media_social\">\r\n");
          out.write("                                              <span><a href=\"#\"><i class=\"fa fa-share-alt\"></i>424 </a> Shares</span>\r\n");
          out.write("                                              <span><i class=\"fa fa-comments-o\"></i><a href=\"#\">4</a> Comments</span>\r\n");
          out.write("                                          </div>\r\n");
          out.write("                                          <!-- media_social -->\r\n");
          out.write("                                      </div>\r\n");
          out.write("                                      <!-- category_article_body -->\r\n");
          out.write("                                  </div>\r\n");
          out.write("                                  <!-- col-md-6 -->\r\n");
          out.write("                              ");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f0.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin.reuse(_jspx_th_c_005fforEach_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f1.setParent(null);
    // /web_front/front_index.jsp(284,34) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f1.setVar("i");
    // /web_front/front_index.jsp(284,34) name = begin type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f1.setBegin(0);
    // /web_front/front_index.jsp(284,34) name = end type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f1.setEnd(1);
    int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
      if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                                  <div class=\"col-md-6\">\r\n");
          out.write("                                      <div class=\"category_article_body\">\r\n");
          out.write("                                          <div class=\"top_article_img\">\r\n");
          out.write("                                              <a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("/product/showProduct?id=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.getTop_computer(i).id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("\" target=\"_self\">\r\n");
          out.write("                                                  <img class=\"img-responsive\" src=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.getTop_computer(i).image}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("\" height=\"700\" width=\"520\" alt=\"feature-top\" />\r\n");
          out.write("                                              </a>\r\n");
          out.write("                                          </div>\r\n");
          out.write("                                          <!-- top_article_img -->\r\n");
          out.write("                                          <span class=\"tag pink\">热销</span>\r\n");
          out.write("                                          <div class=\"category_article_title\">\r\n");
          out.write("                                              <h2><a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("/product/showProduct?id=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.getTop_computer(i).id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("\" target=\"_self\">\r\n");
          out.write("                                                      ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.getTop_computer(i).name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("</a></h2>\r\n");
          out.write("                                          </div>\r\n");
          out.write("                                          <!-- category_article_title -->\r\n");
          out.write("                                          <div class=\"article_date\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.getTop_computer(i).date}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write(" , by: ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.getTop_computer(i).brand}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("</div>\r\n");
          out.write("                                          <!--article_date-->\r\n");
          out.write("                                          <div class=\"category_article_content\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.getTop_computer(i).sketch}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("</div>\r\n");
          out.write("                                          <!-- category_article_content -->\r\n");
          out.write("                                          <div class=\"media_social\">\r\n");
          out.write("                                              <span><a href=\"#\"><i class=\"fa fa-share-alt\"></i>424 </a> Shares</span>\r\n");
          out.write("                                              <span><i class=\"fa fa-comments-o\"></i><a href=\"#\">4</a> Comments</span>\r\n");
          out.write("                                          </div>\r\n");
          out.write("                                          <!-- media_social -->\r\n");
          out.write("                                      </div>\r\n");
          out.write("                                      <!-- category_article_body -->\r\n");
          out.write("                                  </div>\r\n");
          out.write("                                  <!-- col-md-6 -->\r\n");
          out.write("                                  ");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f1.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin.reuse(_jspx_th_c_005fforEach_005f1);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f2 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f2.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f2.setParent(null);
    // /web_front/front_index.jsp(330,34) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f2.setVar("i");
    // /web_front/front_index.jsp(330,34) name = begin type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f2.setBegin(0);
    // /web_front/front_index.jsp(330,34) name = end type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f2.setEnd(1);
    int[] _jspx_push_body_count_c_005fforEach_005f2 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f2 = _jspx_th_c_005fforEach_005f2.doStartTag();
      if (_jspx_eval_c_005fforEach_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                                      <div class=\"col-md-6\">\r\n");
          out.write("                                      <div class=\"category_article_body\">\r\n");
          out.write("                                          <div class=\"top_article_img\">\r\n");
          out.write("                                              <a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("/product/showProduct?id=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.getTop_other(i).id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("\" target=\"_self\">\r\n");
          out.write("                                                  <img class=\"img-responsive\" src=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.getTop_other(i).image}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("\" alt=\"feature-top\" height=\"700\" width=\"520\"/>\r\n");
          out.write("                                              </a>\r\n");
          out.write("                                          </div>\r\n");
          out.write("                                          <!-- top_article_img -->\r\n");
          out.write("                                          <span class=\"tag pink\">热销</span>\r\n");
          out.write("                                          <div class=\"category_article_title\">\r\n");
          out.write("                                              <h2><a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("/product/showProduct?id=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.getTop_other(i).id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("\" target=\"_self\">\r\n");
          out.write("                                                      ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.getTop_other(i).name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("</a></h2>\r\n");
          out.write("                                          </div>\r\n");
          out.write("                                          <!-- category_article_title -->\r\n");
          out.write("                                          <div class=\"article_date\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.getTop_other(i).date}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write(" , by: ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.getTop_other(i).brand}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("</div>\r\n");
          out.write("                                          <!-- article_date -->\r\n");
          out.write("                                          <div class=\"category_article_content\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.getTop_other(i).sketch}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("</div>\r\n");
          out.write("                                          <!-- category_article_content -->\r\n");
          out.write("                                          <div class=\"media_social\">\r\n");
          out.write("                                              <span><a href=\"#\"><i class=\"fa fa-share-alt\"></i>424 </a> Shares</span>\r\n");
          out.write("                                              <span><i class=\"fa fa-comments-o\"></i><a href=\"#\">4</a> Comments</span>\r\n");
          out.write("                                          </div>\r\n");
          out.write("                                          <!-- media_social -->\r\n");
          out.write("                                      </div>\r\n");
          out.write("                                      <!-- category_article_body -->\r\n");
          out.write("                                  </div>\r\n");
          out.write("                                  <!-- col-md-6 -->\r\n");
          out.write("                                  ");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f2[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f2.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f2.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin.reuse(_jspx_th_c_005fforEach_005f2);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f3 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f3.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f3.setParent(null);
    // /web_front/front_index.jsp(381,24) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f3.setVar("i");
    // /web_front/front_index.jsp(381,24) name = begin type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f3.setBegin(0);
    // /web_front/front_index.jsp(381,24) name = end type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f3.setEnd(3);
    int[] _jspx_push_body_count_c_005fforEach_005f3 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f3 = _jspx_th_c_005fforEach_005f3.doStartTag();
      if (_jspx_eval_c_005fforEach_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                            <div class=\"media\">\r\n");
          out.write("                                <div class=\"media-left\">\r\n");
          out.write("                                    <a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("/news/showNews?id=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${news.getNow(i).id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("\" target=\"_self\">\r\n");
          out.write("                                        <img class=\"media-object\" src=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${news.getNow(i).image}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("\" alt=\"Generic placeholder image\" width=\"150\" height=\"100\" /></a>\r\n");
          out.write("                                </div>\r\n");
          out.write("                                <div class=\"media-body\">\r\n");
          out.write("                                    <h3 class=\"media-heading\">\r\n");
          out.write("                                        <a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("/news/showNews?id=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${news.getNow(i).id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("\" target=\"_self\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${news.getNow(i).title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("</a>\r\n");
          out.write("                                    </h3>\r\n");
          out.write("                                    <span class=\"media-date\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${news.getNow(i).date}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write(" , by: ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${news.getNow(i).author}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("</span>\r\n");
          out.write("                                    <div class=\"widget_article_social\">\r\n");
          out.write("                                        <span><a href=\"#\" target=\"_self\"> <i class=\"fa fa-share-alt\"></i>424</a> Shares</span> \r\n");
          out.write("                                        <span><a href=\"#\" target=\"_self\"><i class=\"fa fa-comments-o\"></i>4</a> Comments</span>\r\n");
          out.write("                                    </div>\r\n");
          out.write("                                </div>\r\n");
          out.write("                            </div>\r\n");
          out.write("                        ");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f3[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f3.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f3.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin.reuse(_jspx_th_c_005fforEach_005f3);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f4 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f4.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f4.setParent(null);
    // /web_front/front_index.jsp(423,28) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f4.setVar("i");
    // /web_front/front_index.jsp(423,28) name = begin type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f4.setBegin(0);
    // /web_front/front_index.jsp(423,28) name = end type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f4.setEnd(3);
    int[] _jspx_push_body_count_c_005fforEach_005f4 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f4 = _jspx_th_c_005fforEach_005f4.doStartTag();
      if (_jspx_eval_c_005fforEach_005f4 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                                <div class=\"media\">\r\n");
          out.write("                                    <div class=\"media-left\">\r\n");
          out.write("                                        <a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("/video/showVideo?id=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${video.getTop(i).id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("\" target=\"_self\">\r\n");
          out.write("                                            <img class=\"media-object\" src=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${video.getTop(i).image}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("\" alt=\"Generic placeholder image\" width=\"150\" height=\"100\" /></a>\r\n");
          out.write("                                    </div>\r\n");
          out.write("                                    <div class=\"media-body\">\r\n");
          out.write("                                        <h3 class=\"media-heading\">\r\n");
          out.write("                                            <a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("/video/showVideo?id=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${video.getTop(i).id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("\" target=\"_self\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${video.getTop(i).title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("</a>\r\n");
          out.write("                                        </h3> \r\n");
          out.write("                                        <span class=\"rating\">\r\n");
          out.write("                                            <i class=\"fa fa-star\"></i><i class=\"fa fa-star\"></i><i class=\"fa fa-star\"></i><i class=\"fa fa-star\"></i><i class=\"fa fa-star-half-full\"></i>\r\n");
          out.write("                                        </span>\r\n");
          out.write("                                        <br/><span class=\"media-date\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${video.getTop(i).date}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write(" , by: ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${video.getTop(i).author}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("</span>\r\n");
          out.write("                                    </div>\r\n");
          out.write("                                </div>\r\n");
          out.write("                            ");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f4.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f4[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f4.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f4.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin.reuse(_jspx_th_c_005fforEach_005f4);
    }
    return false;
  }
}
