/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.0-RC5
 * Generated at: 2020-01-02 13:06:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>用户登陆</title>\r\n");
      out.write("\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("\t<meta name=\"keywords\" content=\"\" />\r\n");
      out.write("\t<script type=\"application/x-javascript\"> addEventListener(\"load\", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>\r\n");
      out.write("\t<!-- Custom Theme files -->\r\n");
      out.write("\t<link  rel=\"stylesheet\" type=\"text/css\" href=\"resource/css/style2.css\" media=\"all\" />\r\n");
      out.write("\t<!-- //Custom Theme files -->\r\n");
      out.write("\t<!-- js -->\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"resource/js/jquery.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"resource/js/easyResponsiveTabs.js\" ></script>\r\n");
      out.write("\t<!-- //js -->\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<!-- main -->\r\n");
      out.write("\t<div class=\"main\">\r\n");
      out.write("\t\t<h1>Welcome to TECH!</h1>\r\n");
      out.write("\t\t<div class=\"login-form\">\r\n");
      out.write("\t\t\t<div class=\"sap_tabs w3ls-tabs\">\r\n");
      out.write("\t\t\t\t<div id=\"horizontalTab\" style=\"display: block; width: 100%; margin: 0px;\">\r\n");
      out.write("\t\t\t\t\t<ul class=\"resp-tabs-list\">\r\n");
      out.write("\t\t\t\t\t\t<li class=\"resp-tab-item\" aria-controls=\"tab_item-0\" role=\"tab\"><span>登陆</span></li> \r\n");
      out.write("\t\t\t\t\t\t<li class=\"resp-tab-item\" aria-controls=\"tab_item-1\" role=\"tab\"><label>/</label><span>注册</span></li>\r\n");
      out.write("\t\t\t\t\t</ul>\t\r\n");
      out.write("\t\t\t\t\t<div class=\"clear\"> </div>\r\n");
      out.write("\t\t\t\t\t<div class=\"resp-tabs-container\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"tab-1 resp-tab-content\" aria-labelledby=\"tab_item-0\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"login-agileits-top\"> \r\n");
      out.write("\t\t\t\t\t\t\t\t<form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/front/login\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>账号 </p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"text\" name=\"username\" required=\"required\" id=\"user\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>密码</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"password\" name=\"password\" required=\"required\" id=\"pass\"/>\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<br> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"radio\" id=\"brand\" name=\"k\" value=\"0\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label for=\"brand\"><span></span><font color=\"#F0F0F0\">用户</font> </label> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"radio\" id=\"brand\" name=\"k\" value=\"1\" checked>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label for=\"brand\"><span></span><font color=\"#F0F0F0\">管理员</font> </label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<br/><br/> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"submit\" value=\"LOGIN\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t</form>  \r\n");
      out.write("\t\t\t\t\t\t\t\t<iframe name='login_frame' id=\"login_frame\" style='display: none'></iframe>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"login-agileits-bottom\"> \r\n");
      out.write("\t\t\t\t\t\t\t\t<p><a href=\"#\">忘记密码?</a></p>\r\n");
      out.write("\t\t\t\t\t\t\t</div> \r\n");
      out.write("\t\t\t\t\t\t</div> \r\n");
      out.write("\t\t\t\t\t\t<div class=\"tab-1 resp-tab-content\" aria-labelledby=\"tab_item-1\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"login-agileits-top sign-up\"> \r\n");
      out.write("\t\t\t\t\t\t\t\t<form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/front/register\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>用户名 </p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"text\" name=\"username\"  required=\"required\" id=\"username\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>邮箱 </p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"text\" name=\"email\"  required=\"required\" id=\"email\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>密码</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"password\" name=\"password\" placeholder=\"\" required=\"required\" id=\"password\"/>\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"checkbox\" id=\"brand1\" value=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label for=\"brand1\"><span></span>我接受用户协议</label> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"submit\" value=\"SIGN UP\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</form>  \r\n");
      out.write("\t\t\t\t\t\t\t\t<iframe name='register_frame' id=\"register_frame\" style='display: none'></iframe>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</div>\t \r\n");
      out.write("\t\t\t</div> \r\n");
      out.write("\t\t\t<!-- ResponsiveTabs js -->\r\n");
      out.write("\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t\t$(document).ready(function () {\r\n");
      out.write("\t\t\t\t\t$('#horizontalTab').easyResponsiveTabs({\r\n");
      out.write("\t\t\t\t\t\ttype: 'default', //Types: default, vertical, accordion           \r\n");
      out.write("\t\t\t\t\t\twidth: 'auto', //auto or any width like 600px\r\n");
      out.write("\t\t\t\t\t\tfit: true   // 100% fit in a container\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t</script>\r\n");
      out.write("\t\t\t<!-- //ResponsiveTabs js -->\r\n");
      out.write("\t\t</div>\t\r\n");
      out.write("\t</div>\t\r\n");
      out.write("\t<!-- //main -->\r\n");
      out.write("\t<!-- copyright -->\r\n");
      out.write("\t<div class=\"copyright\">\r\n");
      out.write("\t\t<p> © 2018 Gallery All rights reserved</p>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- //copyright --> \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
